package TA_Recruitment_software.admin_system.model;

/**
 * Summary of a Teaching Assistant's workload.
 * <p>
 * This DTO aggregates TA workload information including assigned position count
 * and total estimated working hours. Generated by {@link TA_Recruitment_software.admin_system.AdminService#listTaWorkloadSummary}.
 * </p>
 * @author Group70
 */
public class TaWorkloadSummary {
    /** TA user ID. */
    private String userId;
    /** TA account ID (login name). */
    private String accountId;
    /** TA full name. */
    private String fullName;
    /** Number of positions assigned (approved/hired/offered). */
    private int assignedPositionCount;
    /** Total estimated working hours across all assigned positions. */
    private double totalAssignedHours;

    /**
     * Creates a new workload summary.
     * @param userId TA user ID
     * @param accountId TA account ID
     * @param fullName TA full name
     * @param assignedPositionCount number of assigned positions
     * @param totalAssignedHours total estimated hours
     */
    public TaWorkloadSummary(String userId, String accountId, String fullName,
                             int assignedPositionCount, double totalAssignedHours) {
        this.userId = userId;
        this.accountId = accountId;
        this.fullName = fullName;
        this.assignedPositionCount = assignedPositionCount;
        this.totalAssignedHours = totalAssignedHours;
    }

    /** @return TA user ID */
    public String getUserId() { return userId; }

    /** @return TA account ID */
    public String getAccountId() { return accountId; }

    /** @return TA full name */
    public String getFullName() { return fullName; }

    /** @return number of assigned positions */
    public int getAssignedPositionCount() { return assignedPositionCount; }

    /** @return total estimated working hours */
    public double getTotalAssignedHours() { return totalAssignedHours; }

    @Override
    public String toString() {
        return "TA Workload{" +
            "userId='" + userId + '\'' +
            ", accountId='" + accountId + '\'' +
            ", fullName='" + fullName + '\'' +
            ", assignedPositionCount=" + assignedPositionCount +
            ", totalAssignedHours=" + totalAssignedHours +
            '}';
    }
}
